### ISSUE TITLE
MALL lab(CD-CS)  vs MLL lab of CSA

### ISSUE THREAD

**Issue by gauravMann** [adi-sharma/DLforNLP-wiki#10]
Is there any difference between the MALL lab (website states for admission apply  under CD-CS stream)
 and the CSA lab ?
If I am not selected in M.Tech(research) under MALL lab can I still work there if I get in through M.tech(CSA) ?
Thank you.

**Comment by svjan5** [comment]
I don't think this is the right forum for this. Please contact Aditya (http://adityasharma.space/).
